### ISSUE TITLE
[FEATURE] Help command style

### ISSUE THREAD

**Issue by killerclaws12** [onesoft-sudo/sudobot#103]
For the help command, divide the pages into categories. For instance, the first page is fun commands, 2nd page is moderation, 3rd page is auto-moderation and etc.

**Comment by virtual-designer** [comment]
Well I'm thinking to use select menus for that with the buttons. What do you think?

**Comment by killerclaws12** [comment]
I dont really like select menus
They look ugly imo same as a dropdown.

**Comment by virtual-designer** [comment]
> I dont really like select menus They look ugly imo same as a dropdown.

But we already have a row of buttons. It is possible to add another row of buttons for the categories, but that would look ugly, right?

**Comment by killerclaws12** [comment]
i dunno

**Comment by virtual-designer** [comment]
> i dunno

Okay don't worry, I will show the screenshots of both scenarios when I work on it.
