### ISSUE TITLE
[FEATURE] Ticket System

### ISSUE THREAD

**Issue by killerclaws12** [onesoft-sudo/sudobot#111]
Ticket system. Come on. Who doesn't like tickets?

**Comment by killerclaws12** [comment]
like ticketool.xyz but better

**Comment by killerclaws12** [comment]
customizable

**Comment by virtual-designer** [comment]
To be honest, SudoBot is most of the times focused on Moderation, plus we already have MailBot for tickets. So I don't want to add ticket systems on SudoBot.

There's another reason - SudoBot is a multi guild bot, if a user shares multiple servers and opens a ticket (by DMing) then we need to show the guild selection option to them. Which is a pain for the user to select guilds everytime.

You can say that use a channel on guilds where users can create tickets. But again we already have a ticket bot.

**Comment by killerclaws12** [comment]
But aint nobody gonna use mailbot. More people gonna use sudobot so it should come with tickets.

**Comment by virtual-designer** [comment]
I will think about it.
