### ISSUE TITLE
[FEATURE] Setup command

### ISSUE THREAD

**Issue by killerclaws12** [onesoft-sudo/sudobot#120]
When a user runs setup command, the bot will check if it has right permissions, it will say "Want to setup the mute role?" and blah blah blah, and etc. Then "Want to setup logs?" etc. Just like wick bot.

**Comment by virtual-designer** [comment]
> It will say "Want to setup the mute role?"

Yes, it's a good idea. I will start working on it soon :)

> Then "Want to setup logs?" etc. Just like wick bot.

For that we will have the dashboard. For now users can adjust those values in the config file or by using `/config` command.

**Comment by virtual-designer** [comment]
Completed.
