### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lITronusIl** [onesoft-sudo/sudobot#128]
im getting following error: sudobot@4.82.2 start
26.04 13:18:01 [Bot] pm2 start ./ecosystem.config.js --no-daemon
26.04 13:18:01 [Bot] /tmp/start-efa8eccc.sh: 1: pm2: not found
26.04 13:18:02 [PebbleHost] Server shut down (running)

**Comment by virtual-designer** [comment]
Did you run `npm install -D` before starting the bot? The `pm2` command only works if the dependencies are installed correctly.

**Comment by ninsaccplayzyt** [comment]
this has been open for like a year now

**Comment by bimoware** [comment]
why isn't this closed lmao

**Comment by virtual-designer** [comment]
Closed as invalid.
