### ISSUE TITLE
No script called build [BUG] 

### ISSUE THREAD

**Issue by Otf5shotzz** [onesoft-sudo/sudobot#131]
PS C:\Users\???\Downloads\sudobot-main> npm run build
npm ERR! Missing script: "build"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: C:\Users\???\AppData\Local\npm-cache\_logs\2023-04-27T21_55_17_656Z-debug-0.log

**Comment by virtual-designer** [comment]
Have you cloned the repository correctly? What is output of `cat package.json`?
