### ISSUE TITLE
[FEATURE] Add the hover effect to the button

### ISSUE THREAD

**Issue by Manmit124** [onesoft-sudo/sudobot#138]
Add the Hover to the button in home page 
![image](https://github.com/onesoft-sudo/sudobot/assets/112580293/3fa2ad6e-9c7d-4b42-afef-af937c4bfa6d)

**Comment by virtual-designer** [comment]
Hey Manmit, 
Thanks for your suggestion! We'll add hover effects to those buttons soon.
