### ISSUE TITLE
[BUG] UI Layout Changing error

### ISSUE THREAD

**Issue by Manmit124** [onesoft-sudo/sudobot#139]
**Describe the bug**
Changing the Card box layout 

**To Reproduce**
1. Go to 'Community Reviews'
2. Click on 'Next Or Back Button'
3. See error

Whenever we click on the Next or Back button of Community Reviews the footer goes up down  his changing their layout that is bad experience for the user 

video:https://github.com/onesoft-sudo/sudobot/assets/112580293/7b936036-2363-4468-b0aa-59db559ed011

**Comment by virtual-designer** [comment]
Hey Manmit,
Once again thanks for reporting the issue!
I'll be pushing a fix to this tomorrow.

And just a little note, it'd be good if you submit your issues/PRs for the dashboard in it's own repository: https://github.com/onesoft-sudo/sudobot-dashboard
