### ISSUE TITLE
[FEATURE] Custom "say hi" message support in Welcomer Service

### ISSUE THREAD

**Issue by DesignAny** [onesoft-sudo/sudobot#142]
**Is your feature request related to a problem? Please describe.**
Added the ability to change the answer after clicking the greeting button

**Describe the solution you'd like**
Custom file example:  config.json { "say_hi_replay": "Welcome", } 
(If it were possible, add such a line of code to each module where the answers can be changed in)

**Describe alternatives you've considered**
Custom file example: CustomAwnser.json - to set own awnser or Language.json to custom message all modules

**Additional context**
![obraz](https://github.com/onesoft-sudo/sudobot/assets/89824974/b3322431-0016-43aa-bcfc-6486d2d35b13)
![obraz](https://github.com/onesoft-sudo/sudobot/assets/89824974/c14b213e-4298-4ebb-997d-1c6ee00edb86)

**Comment by virtual-designer** [comment]
Hello,

Thanks a lot for suggesting this feature! I'll be implementing this in a few days, and it will be available in the next release. Stay tuned!
