### ISSUE TITLE
[BUG] The table `public.global_user_bans` does not exist in the current database.

### ISSUE THREAD

**Issue by sipertowny** [onesoft-sudo/sudobot#164]
**Describe the bug**

**To Reproduce**
1. npm start
2. then see the error

**Screenshots**
![image](https://github.com/onesoft-sudo/sudobot/assets/166100752/9411238a-d6d2-4124-975b-2311c1506663)

**Environment**
- NodeJS version: 20.12.2
- TypeScript version: idk how to check

**Comment by ninsaccplayzyt** [comment]
When setting up, did you remember to run `npx prisma db push` to set up the database?

**Comment by ninsaccplayzyt** [comment]
If you did, then I suggest trying again seeing as it should just set up every database upon running the command. This is my database where it has already been put there.
![image](https://github.com/onesoft-sudo/sudobot/assets/95270582/164ad6f3-ff13-47bb-add3-a0fad712eb86)

**Comment by sipertowny** [comment]
> When setting up, did you remember to run `npx prisma db push` to set up the database?

shiet i forgot it thank youuuuu

**Comment by ninsaccplayzyt** [comment]
Lol it happens sometimes. You're welcome for that and make to read [docs](https://docs.sudobot.org/getting-started) carefully so this doesn't happen again lol.

**Comment by virtual-designer** [comment]
> > When setting up, did you remember to run `npx prisma db push` to set up the database?
> 
> shiet i forgot it thank youuuuu

Closing as completed.
