### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by Xarond** [onesoft-sudo/sudobot#166]
![image](https://github.com/onesoft-sudo/sudobot/assets/59401139/255377a7-46e8-4c0d-97bc-76b0d06ff14e)

**Comment by Xarond** [comment]
happens when running npm install -D

**Comment by virtual-designer** [comment]
Please run:

`npm remove bufferutil zlib-sync && npm install -D`

**Comment by ninsaccplayzyt** [comment]
hey @Xarond, have you fixed this yet?

**Comment by ninsaccplayzyt** [comment]
over a month since last response from user, closing issue as assuming its fixed
