### ISSUE TITLE
./blazew build wont work

### ISSUE THREAD

**Issue by bloodieee** [onesoft-sudo/sudobot#180]
I am using Windows 10

465gb c drive total
177gb free
8gb ram

**Comment by virtual-designer** [comment]
Since we've discussed about this in our Discord server, I'll leave this open for now.

**Comment by virtual-designer** [comment]
The issue was mainly trying to use BlazeBuild on an unsupported system. But, windows support is now officially available, starting from `v9.17.4`. Closing as completed.
