### ISSUE TITLE
[BUG] Build Successfully, but the blazebuild folder is emptied after the build

### ISSUE THREAD

**Issue by 6despise** [onesoft-sudo/sudobot#187]
BUILD SUCCESSFUL in 5m 52.17s
7 actionable tasks: 7 executed

PS C:\Users\Cjeck\sudobot> ./blazew run -- -- -u -g
warn   Node.js global version mismatch: required 22.4.1, found 20.15.1
info   Installing BlazeBuild dependencies...
[0.00ms] ".env"
bun install v1.1.20 (ae194892)

$ husky && rm -fr node_modules/blazebuild && node -e "const { symlinkSync } = require('fs'); const path = require('path'); symlinkSync(path.join(process.cwd(), 'blazebuild'), path.join(process.cwd(), 'node_modules/blazebuild'), 'dir');"

Checked 766 installs across 811 packages (no changes) [12.72s]
error: Failed to find entry file for execution in directory: C:\Users\Cjeck\sudobot\blazebuild (Path: C:\Users\Cjeck\sudobot\blazebuild/src/main/typescript/cli.ts)
PS C:\Users\Cjeck\sudobot>

**Comment by ninsaccplayzyt** [comment]
this is definitely a weird issue, i take it that this would only happen on windows, @virtual-designer maybe you can figure this out

**Comment by bloodieee** [comment]
> this is definitely a weird issue, i take it that this would only happen on windows, @virtual-designer maybe you can figure this out

i'll try to use wsl
and see if it work

**Comment by ninsaccplayzyt** [comment]
> i'll try to use wsl

alright, let me know how that goes

**Comment by 6despise** [comment]
> > i'll try to use wsl
> 
> alright, let me know how that goes

nothing happens LOL
![image](https://github.com/user-attachments/assets/cceb6c0e-0c75-434b-a16a-b5e3b29fa472)

**Comment by ninsaccplayzyt** [comment]
> nothing happens LOL ![image](https://private-user-images.githubusercontent.com/172607771/352714097-cceb6c0e-0c75-434b-a16a-b5e3b29fa472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzQwNTQsIm5iZiI6MTcyMjA3Mzc1NCwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyNzE0MDk3LWNjZWI2YzBlLTBjNzUtNDM0Yi1hMTZhLWI1ZTNiMjlmYTQ3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwOTQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODJkMDc4YTYyMGE2MDU2ZTg4NGNhYTdiYjQxYzQwZDdmYjFmYTQxNjIyOWQxMWE2ZGRkZGQ5MTk0MmI5ZTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dugqfsLah7GsricH5Ez4jT285BM8EAp9lyu7OMxj-sY)

try run it again maybe? it did say installing bun version 1.1.20

**Comment by virtual-designer** [comment]
Have you updated your instance to latest? I've made some changes to BlazeBuild too.

**Comment by virtual-designer** [comment]
Have you updated your instance to latest? I've made some changes to BlazeBuild too.

**Comment by virtual-designer** [comment]
> this is definitely a weird issue, i take it that this would only happen on windows, @virtual-designer maybe you can figure this out

Not anymore cause Windows is supported now.

**Comment by ninsaccplayzyt** [comment]
> Not anymore cause Windows is supported now.

yeah ive heard that windows is supported, but that is definitely a weird issue that happened

**Comment by 6despise** [comment]
@virtual-designer I need help with the tabs, they're not working
![image](https://github.com/user-attachments/assets/d2d84fad-d7bb-477f-950b-96df6056085b)
![image](https://github.com/user-attachments/assets/c2fd7e40-ba28-46ae-b0ee-93a862c14133)

**Comment by ninsaccplayzyt** [comment]
> @virtual-designer I need help with the tabs, they're not working ![image](https://private-user-images.githubusercontent.com/172607771/352800197-d2d84fad-d7bb-477f-950b-96df6056085b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjEyMDEsIm5iZiI6MTcyMjE2MDkwMSwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyODAwMTk3LWQyZDg0ZmFkLWQ3YmItNDc3Zi05NTBiLTk2ZGY2MDU2MDg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzA2OWE4ZGExNmY4YjQwNTNlNTE1NWQwY2JkZDZjNjIyOTRjYTM3N2E0NGJhYWY4YzA4M2Q0Zjc4N2ZiMzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iljaPFklnK6wiuqj0iBpxrnWbcv4aZrlLDaI9m-D7GI) ![image](https://private-user-images.githubusercontent.com/172607771/352800208-c2fd7e40-ba28-46ae-b0ee-93a862c14133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjEyMDEsIm5iZiI6MTcyMjE2MDkwMSwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyODAwMjA4LWMyZmQ3ZTQwLWJhMjgtNDZhZS1iMGVlLTkzYTg2MmMxNDEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODM2OTQ5ODgzNGExZDc0YTg5YTE0ZDYwYjY2ZjdkNTgzMmUzMjk1ODNmM2NhOTY3OGI2NWY0ODdhNDNlZjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5XzagZkuLAJCAZn3T1_xNX3KXUefvTgARCIo6UL2W_4)

is this on the dashboard? if so, i dont think the dashboard is fully ready for production use yet as its still being worked on iirc

**Comment by 6despise** [comment]
> > @virtual-designer I need help with the tabs, they're not working ![image](https://private-user-images.githubusercontent.com/172607771/352800197-d2d84fad-d7bb-477f-950b-96df6056085b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjEyMDEsIm5iZiI6MTcyMjE2MDkwMSwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyODAwMTk3LWQyZDg0ZmFkLWQ3YmItNDc3Zi05NTBiLTk2ZGY2MDU2MDg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzA2OWE4ZGExNmY4YjQwNTNlNTE1NWQwY2JkZDZjNjIyOTRjYTM3N2E0NGJhYWY4YzA4M2Q0Zjc4N2ZiMzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iljaPFklnK6wiuqj0iBpxrnWbcv4aZrlLDaI9m-D7GI) ![image](https://private-user-images.githubusercontent.com/172607771/352800208-c2fd7e40-ba28-46ae-b0ee-93a862c14133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjEyMDEsIm5iZiI6MTcyMjE2MDkwMSwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyODAwMjA4LWMyZmQ3ZTQwLWJhMjgtNDZhZS1iMGVlLTkzYTg2MmMxNDEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODM2OTQ5ODgzNGExZDc0YTg5YTE0ZDYwYjY2ZjdkNTgzMmUzMjk1ODNmM2NhOTY3OGI2NWY0ODdhNDNlZjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5XzagZkuLAJCAZn3T1_xNX3KXUefvTgARCIo6UL2W_4)
> 
> is this on the dashboard? if so, i dont think the dashboard is fully ready for production use yet as its still being worked on iirc

oh ok

**Comment by virtual-designer** [comment]
> > > @virtual-designer I need help with the tabs, they're not working ![image](https://private-user-images.githubusercontent.com/172607771/352800197-d2d84fad-d7bb-477f-950b-96df6056085b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjEyMDEsIm5iZiI6MTcyMjE2MDkwMSwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyODAwMTk3LWQyZDg0ZmFkLWQ3YmItNDc3Zi05NTBiLTk2ZGY2MDU2MDg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzA2OWE4ZGExNmY4YjQwNTNlNTE1NWQwY2JkZDZjNjIyOTRjYTM3N2E0NGJhYWY4YzA4M2Q0Zjc4N2ZiMzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iljaPFklnK6wiuqj0iBpxrnWbcv4aZrlLDaI9m-D7GI) ![image](https://private-user-images.githubusercontent.com/172607771/352800208-c2fd7e40-ba28-46ae-b0ee-93a862c14133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjEyMDEsIm5iZiI6MTcyMjE2MDkwMSwicGF0aCI6Ii8xNzI2MDc3NzEvMzUyODAwMjA4LWMyZmQ3ZTQwLWJhMjgtNDZhZS1iMGVlLTkzYTg2MmMxNDEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMDAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODM2OTQ5ODgzNGExZDc0YTg5YTE0ZDYwYjY2ZjdkNTgzMmUzMjk1ODNmM2NhOTY3OGI2NWY0ODdhNDNlZjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5XzagZkuLAJCAZn3T1_xNX3KXUefvTgARCIo6UL2W_4)
> > 
> > 
> > is this on the dashboard? if so, i dont think the dashboard is fully ready for production use yet as its still being worked on iirc
> 
> aight

Yeah, I've said this before too.

**Comment by virtual-designer** [comment]
> BUILD SUCCESSFUL in 5m 52.17s 7 actionable tasks: 7 executed
> 
> PS C:\Users\Cjeck\sudobot> ./blazew run -- -- -u -g warn Node.js global version mismatch: required 22.4.1, found 20.15.1 info Installing BlazeBuild dependencies... [0.00ms] ".env" bun install v1.1.20 (ae194892)
> 
> $ husky && rm -fr node_modules/blazebuild && node -e "const { symlinkSync } = require('fs'); const path = require('path'); symlinkSync(path.join(process.cwd(), 'blazebuild'), path.join(process.cwd(), 'node_modules/blazebuild'), 'dir');"
> 
> Checked 766 installs across 811 packages (no changes) [12.72s] error: Failed to find entry file for execution in directory: C:\Users\Cjeck\sudobot\blazebuild (Path: C:\Users\Cjeck\sudobot\blazebuild/src/main/typescript/cli.ts) PS C:\Users\Cjeck\sudobot>

As for the explanation on why this issue had occurred, it was because the inline JavaScript code that the postinstall script runs each time after dependency changes. In the inline code I forgot to add checks and make sure to not remove the symbolic link recursively, which behaves differently in Windows systems, removing the path which the link points to. Comparing this to a Linux/Unix based system, it would rather just remove the symbolic link and not modify the original path.

This issue has been addressed in the latest releases. 
I'll be closing this issue. Feel free to create a new one if you have any further issues.
