### ISSUE TITLE
Create an installer script

### ISSUE THREAD

**Issue by virtual-designer** [onesoft-sudo/sudobot#89]
Create an installer script which will generate a config file according to the user's input.

**Comment by Ladam0203** [comment]
Would this be a command line installer or something fancier?

**Comment by virtual-designer** [comment]
It's just a command line installer, which will ask the user about some required config options, and then write them to the config file (`config/config.json`).

The required config options are:
- Prefix `prefix`
- Moderator role `mod_role`
- Owners
- Home Guild ID
- Admin role `admin`
- Muted Role `mute_role`

I've already created the script [`setup.js`](https://github.com/onesoft-sudo/sudobot/tree/main/setup.js) but this issue is still open because the script is still not fully ready for use.

**Comment by Ladam0203** [comment]
I will take a look at this rightaway! :)
